version: "3.8"
services:
  database:
    image: postgres:9.6.21-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crud
    ports:
      - "9001:5432"
    volumes:
      - ./pg-crud:/var/lib/postgresql/data
    container_name: postgresdb