version: "3.8"
services:
  database:
    image: postgres:9.6.21-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "9001:5432"
    volumes:
      - ./pg-crud:/var/lib/postgresql/data
    container_name: postgresdb