version: "3.8"
services:
  database:
    image: postgres:9.6.21-alpine
    restart: always
    environment:
      - POSTGRES_USER=danang
      - POSTGRES_PASSWORD=danang
      - POSTGRES_DB=crud
    ports:
      - "9001:5432"
    volumes:
      - ./pg-crud:/var/lib/postgresql/data
    container_name: postgresdb
  # mysql:
  #   image: mysql:5.7
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   ports:
  #     - "9001:3306"
  #   # networks:
  #   #   - gin_backend
  #   environment:
  #     - MYSQL_USER=danang
  #     - MYSQL_ROOT_PASSWORD=danang
  #     - MYSQL_PASSWORD=danang 
  #     - MYSQL_DATABASE=crud
  #   volumes: 
  #     - ./db-mysql:/var/lib/mysql
  #   container_name: go_mysql